<?xml version='1.0' encoding='utf-8'?><!DOCTYPE Countries [    <!ELEMENT Country (ISO3, ShortName, LongName, Notes, Capital, TypeMem, UNESCOdate, Langcoresp, Regions, Groups)>    <!ELEMENT ISO3 (#PCDATA)>    <!ELEMENT ShortName (#PCDATA)>    <!ELEMENT LongName (#PCDATA)>    <!ELEMENT Notes (#PCDATA)>    <!ELEMENT Capital (#PCDATA)>    <!ELEMENT TypeMem (#PCDATA)>    <!ELEMENT UNESCOdate (#PCDATA)>    <!ELEMENT Langcoresp (#PCDATA)>    <!ELEMENT Holiday (#PCDATA)>    <!ELEMENT Regions (Region)>    <!ELEMENT Region (#PCDATA)>    <!ELEMENT Groups (Group)>    <!ELEMENT GroupEB (#PCDATA)>    <!ELEMENT LDC (#PCDATA)>    <!ELEMENT SMS (#PCDATA)>    <!ELEMENT Geneve (#PCDATA)>    <!ELEMENT OCDE (#PCDATA)>    <!ELEMENT Group77 (#PCDATA)>    <!ELEMENT Russophone (#PCDATA)>    <!ELEMENT E9 (#PCDATA)>    <!ELEMENT Geneve (#PCDATA)>    <!ATTLIST Country countryid ID #REQUIRED>    <!ATTLIST ShortName xml:lang (en|fr|es|ar) "en" >    <!ATTLIST LongName xml:lang (en|fr|es|ar) "en" >    <!ATTLIST Notes xml:lang (en|fr|es|ar) "en" >    <!ATTLIST TypeMem xml:lang (en|fr|es) "en" >    <!ATTLIST Region xml:lang (en|fr|es) "en" >]>
<Countries>
    <Country countryid="AD">
        <ISO3 xml:lang="en">AND</ISO3>
        <ShortName xml:lang="en">Andorra</ShortName>
        <ShortName xml:lang="fr">Andorre</ShortName>
        <ShortName xml:lang="es">Andorra</ShortName>
        <LongName xml:lang="en">the Principality of Andorra</LongName>
        <LongName xml:lang="fr">la Principauté d'Andorre</LongName>
        <LongName xml:lang="es">el Principado de Andorra</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Andorra la Vella</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1993-10-20</UNESCOdate>
        <Holiday>2011-9-8</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>I</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77></Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="AE">
        <ISO3 xml:lang="en">ARE</ISO3>
        <ShortName xml:lang="en">United Arab Emirates</ShortName>
        <ShortName xml:lang="fr">Émirats arabes unis</ShortName>
        <ShortName xml:lang="es">Emiratos Arabes Unidos</ShortName>
        <LongName xml:lang="en">the United Arab Emirates</LongName>
        <LongName xml:lang="fr">Émirats arabes unis (les)</LongName>
        <LongName xml:lang="es">Emiratos Arabes Unidos (los)</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Abu Dhabi</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1972-4-20</UNESCOdate>
        <Holiday>2011-12-2</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>Vb</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Arab States</Region>
            <Region xml:lang="fr">Etats arabes</Region>
            <Region xml:lang="es">Estados Arabes</Region>
        </Regions>
    </Country>
    <Country countryid="AF">
        <ISO3 xml:lang="en">AFG</ISO3>
        <ShortName xml:lang="en">Afghanistan</ShortName>
        <ShortName xml:lang="fr">Afghanistan</ShortName>
        <ShortName xml:lang="es">Afganistán</ShortName>
        <LongName xml:lang="en">the Islamic Republic of Afghanistan</LongName>
        <LongName xml:lang="fr">la République islamique d'Afghanistan</LongName>
        <LongName xml:lang="es">República Islámica del Afganistán (la)</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Kabul</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1948-5-4</UNESCOdate>
        <Holiday>2011-8-19</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>IV</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Asia and the Pacific</Region>
            <Region xml:lang="fr">Asie et Pacifique</Region>
            <Region xml:lang="es">Asia y el Pacifico</Region>
        </Regions>
    </Country>
    <Country countryid="AG">
        <ISO3 xml:lang="en">ATG</ISO3>
        <ShortName xml:lang="en">Antigua and Barbuda</ShortName>
        <ShortName xml:lang="fr">Antigua-et-Barbuda</ShortName>
        <ShortName xml:lang="es">Antigua y Barbuda</ShortName>
        <LongName xml:lang="en">Antigua and Barbuda</LongName>
        <LongName xml:lang="fr">Antigua-et-Barbuda</LongName>
        <LongName xml:lang="es">Antigua y Barbuda</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Saint John's</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1982-7-15</UNESCOdate>
        <Holiday>2011-11-1</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>III</GroupEB>
            <LDC></LDC>
            <SMS>1</SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Latin America and the Caribbean</Region>
            <Region xml:lang="fr">Amérique latine et Caraïbes</Region>
            <Region xml:lang="es">América Latina y el Caribe</Region>
        </Regions>
    </Country>
    <Country countryid="AL">
        <ISO3 xml:lang="en">ALB</ISO3>
        <ShortName xml:lang="en">Albania</ShortName>
        <ShortName xml:lang="fr">Albanie</ShortName>
        <ShortName xml:lang="es">Albania</ShortName>
        <LongName xml:lang="en">the Republic of Albania</LongName>
        <LongName xml:lang="fr">la République d'Albanie</LongName>
        <LongName xml:lang="es">la República de Albania</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Tirana</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1958-10-16</UNESCOdate>
        <Holiday>2011-11-28</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>II</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77></Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="AM">
        <ISO3 xml:lang="en">ARM</ISO3>
        <ShortName xml:lang="en">Armenia</ShortName>
        <ShortName xml:lang="fr">Arménie</ShortName>
        <ShortName xml:lang="es">Armenia</ShortName>
        <LongName xml:lang="en">the Republic of Armenia</LongName>
        <LongName xml:lang="fr">la République d'Arménie</LongName>
        <LongName xml:lang="es">la República de Armenia</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Yerevan</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1992-6-9</UNESCOdate>
        <Holiday>2011-9-21</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>II</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77></Group77>
            <Russophone>1</Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="AO">
        <ISO3 xml:lang="en">AGO</ISO3>
        <ShortName xml:lang="en">Angola</ShortName>
        <ShortName xml:lang="fr">Angola</ShortName>
        <ShortName xml:lang="es">Angola</ShortName>
        <LongName xml:lang="en">the Republic of Angola</LongName>
        <LongName xml:lang="fr">la République d'Angola</LongName>
        <LongName xml:lang="es">la República de Angola</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Luanda</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1977-3-11</UNESCOdate>
        <Holiday>2011-11-11</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>Va</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Africa</Region>
            <Region xml:lang="fr">Afrique</Region>
            <Region xml:lang="es">África</Region>
        </Regions>
    </Country>
    <Country countryid="AR">
        <ISO3 xml:lang="en">ARG</ISO3>
        <ShortName xml:lang="en">Argentina</ShortName>
        <ShortName xml:lang="fr">Argentine</ShortName>
        <ShortName xml:lang="es">Argentina</ShortName>
        <LongName xml:lang="en">the Argentine Republic</LongName>
        <LongName xml:lang="fr">la République argentine</LongName>
        <LongName xml:lang="es">la República Argentina</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Buenos Aires</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1948-9-15</UNESCOdate>
        <Holiday>2011-5-25</Holiday>
        <Langcoresp>es</Langcoresp>
        <Groups>
            <GroupEB>III</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Latin America and the Caribbean</Region>
            <Region xml:lang="fr">Amérique latine et Caraïbes</Region>
            <Region xml:lang="es">América Latina y el Caribe</Region>
        </Regions>
    </Country>
    <Country countryid="AT">
        <ISO3 xml:lang="en">AUT</ISO3>
        <ShortName xml:lang="en">Austria</ShortName>
        <ShortName xml:lang="fr">Autriche</ShortName>
        <ShortName xml:lang="es">Austria</ShortName>
        <LongName xml:lang="en">the Republic of Austria</LongName>
        <LongName xml:lang="fr">la République d'Autriche</LongName>
        <LongName xml:lang="es">la República de Austria</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Vienna</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1948-8-13</UNESCOdate>
        <Holiday>2011-10-26</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>I</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE>1</OCDE>
            <Group77></Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="AU">
        <ISO3 xml:lang="en">AUS</ISO3>
        <ShortName xml:lang="en">Australia</ShortName>
        <ShortName xml:lang="fr">Australie</ShortName>
        <ShortName xml:lang="es">Australia</ShortName>
        <LongName xml:lang="en">Australia</LongName>
        <LongName xml:lang="fr">Australie</LongName>
        <LongName xml:lang="es">Australia</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Canberra ACT</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1946-11-4</UNESCOdate>
        <Holiday>2011-1-26</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>IV</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve>1</Geneve>
            <OCDE>1</OCDE>
            <Group77></Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Asia and the Pacific</Region>
            <Region xml:lang="fr">Asie et Pacifique</Region>
            <Region xml:lang="es">Asia y el Pacifico</Region>
        </Regions>
    </Country>
    <Country countryid="AZ">
        <ISO3 xml:lang="en">AZE</ISO3>
        <ShortName xml:lang="en">Azerbaijan</ShortName>
        <ShortName xml:lang="fr">Azerbaïdjan</ShortName>
        <ShortName xml:lang="es">Azerbaiyán</ShortName>
        <LongName xml:lang="en">the Republic of Azerbaijan</LongName>
        <LongName xml:lang="fr">la République d'Azerbaïdjan</LongName>
        <LongName xml:lang="es">la República de Azerbaiyán</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Bakou</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1992-6-3</UNESCOdate>
        <Holiday>2011-5-28</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>II</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77></Group77>
            <Russophone>1</Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="BA">
        <ISO3 xml:lang="en">BIH</ISO3>
        <ShortName xml:lang="en">Bosnia and Herzegovina</ShortName>
        <ShortName xml:lang="fr">Bosnie-Herzégovine</ShortName>
        <ShortName xml:lang="es">Bosnia y Herzegovina</ShortName>
        <LongName xml:lang="en">Bosnia and Herzegovina</LongName>
        <LongName xml:lang="fr">Bosnie-Herzégovine</LongName>
        <LongName xml:lang="es">Bosnia y Herzegovina</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Sarajevo</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1993-6-2</UNESCOdate>
        <Holiday>2011-11-21</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>II</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="BB">
        <ISO3 xml:lang="en">BRB</ISO3>
        <ShortName xml:lang="en">Barbados</ShortName>
        <ShortName xml:lang="fr">Barbade</ShortName>
        <ShortName xml:lang="es">Barbados</ShortName>
        <LongName xml:lang="en">Barbados</LongName>
        <LongName xml:lang="fr">Barbade</LongName>
        <LongName xml:lang="es">Barbados</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Bridgetown</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1968-10-24</UNESCOdate>
        <Holiday>2011-11-30</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>III</GroupEB>
            <LDC></LDC>
            <SMS>1</SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Latin America and the Caribbean</Region>
            <Region xml:lang="fr">Amérique latine et Caraïbes</Region>
            <Region xml:lang="es">América Latina y el Caribe</Region>
        </Regions>
    </Country>
    <Country countryid="BD">
        <ISO3 xml:lang="en">BGD</ISO3>
        <ShortName xml:lang="en">Bangladesh</ShortName>
        <ShortName xml:lang="fr">Bangladesh</ShortName>
        <ShortName xml:lang="es">Bangladesh</ShortName>
        <LongName xml:lang="en">the People's Republic of Bangladesh</LongName>
        <LongName xml:lang="fr">la République populaire du Bangladesh</LongName>
        <LongName xml:lang="es">la República Popular de Bangladesh</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Dhaka</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1972-10-27</UNESCOdate>
        <Holiday>2011-3-26</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>IV</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9>1</E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Asia and the Pacific</Region>
            <Region xml:lang="fr">Asie et Pacifique</Region>
            <Region xml:lang="es">Asia y el Pacifico</Region>
        </Regions>
    </Country>
    <Country countryid="BE">
        <ISO3 xml:lang="en">BEL</ISO3>
        <ShortName xml:lang="en">Belgium</ShortName>
        <ShortName xml:lang="fr">Belgique</ShortName>
        <ShortName xml:lang="es">Bélgica</ShortName>
        <LongName xml:lang="en">the Kingdom of Belgium</LongName>
        <LongName xml:lang="fr">le Royaume de Belgique</LongName>
        <LongName xml:lang="es">el Reino de Bélgica</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Bruxelles</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1946-11-29</UNESCOdate>
        <Holiday>2011-7-21</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>I</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve>1</Geneve>
            <OCDE>1</OCDE>
            <Group77></Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="BF">
        <ISO3 xml:lang="en">BFA</ISO3>
        <ShortName xml:lang="en">Burkina Faso</ShortName>
        <ShortName xml:lang="fr">Burkina Faso</ShortName>
        <ShortName xml:lang="es">Burkina Faso</ShortName>
        <LongName xml:lang="en">Burkina Faso</LongName>
        <LongName xml:lang="fr">Burkina Faso</LongName>
        <LongName xml:lang="es">Burkina Faso</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Ouagadougou</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1960-11-14</UNESCOdate>
        <Holiday>2011-12-11</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>Va</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Africa</Region>
            <Region xml:lang="fr">Afrique</Region>
            <Region xml:lang="es">África</Region>
        </Regions>
    </Country>
    <Country countryid="BG">
        <ISO3 xml:lang="en">BGR</ISO3>
        <ShortName xml:lang="en">Bulgaria</ShortName>
        <ShortName xml:lang="fr">Bulgarie</ShortName>
        <ShortName xml:lang="es">Bulgaria</ShortName>
        <LongName xml:lang="en">the Republic of Bulgaria</LongName>
        <LongName xml:lang="fr">la République de Bulgarie</LongName>
        <LongName xml:lang="es">la República de Bulgaria</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Sofia</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1956-5-17</UNESCOdate>
        <Holiday>2011-3-3</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>II</GroupEB>
            <LDC></LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77></Group77>
            <Russophone>1</Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Europe and North America</Region>
            <Region xml:lang="fr">Europe et Amérique du nord</Region>
            <Region xml:lang="es">Europa y América del Norte</Region>
        </Regions>
    </Country>
    <Country countryid="BH">
        <ISO3 xml:lang="en">BHR</ISO3>
        <ShortName xml:lang="en">Bahrain</ShortName>
        <ShortName xml:lang="fr">Bahreïn</ShortName>
        <ShortName xml:lang="es">Bahrein</ShortName>
        <LongName xml:lang="en">the Kingdom of Bahrain</LongName>
        <LongName xml:lang="fr">le Royaume de Bahreïn</LongName>
        <LongName xml:lang="es">el Reino de Bahrein</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Manama</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1972-1-18</UNESCOdate>
        <Holiday>2011-12-16</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>Vb</GroupEB>
            <LDC></LDC>
            <SMS>1</SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Arab States</Region>
            <Region xml:lang="fr">Etats arabes</Region>
            <Region xml:lang="es">Estados Arabes</Region>
        </Regions>
    </Country>
    <Country countryid="BI">
        <ISO3 xml:lang="en">BDI</ISO3>
        <ShortName xml:lang="en">Burundi</ShortName>
        <ShortName xml:lang="fr">Burundi</ShortName>
        <ShortName xml:lang="es">Burundi</ShortName>
        <LongName xml:lang="en">the Republic of Burundi</LongName>
        <LongName xml:lang="fr">la République du Burundi</LongName>
        <LongName xml:lang="es">la República de Burundi</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Bujumbura</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1962-11-16</UNESCOdate>
        <Holiday>2011-7-1</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>Va</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Africa</Region>
            <Region xml:lang="fr">Afrique</Region>
            <Region xml:lang="es">África</Region>
        </Regions>
    </Country>
    <Country countryid="BJ">
        <ISO3 xml:lang="en">BEN</ISO3>
        <ShortName xml:lang="en">Benin</ShortName>
        <ShortName xml:lang="fr">Bénin</ShortName>
        <ShortName xml:lang="es">Benin</ShortName>
        <LongName xml:lang="en">the Republic of Benin</LongName>
        <LongName xml:lang="fr">la République du Bénin</LongName>
        <LongName xml:lang="es">la República de Benin</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Porto Novo</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>1960-10-18</UNESCOdate>
        <Holiday>2011-8-1</Holiday>
        <Langcoresp>fr</Langcoresp>
        <Groups>
            <GroupEB>Va</GroupEB>
            <LDC>1</LDC>
            <SMS></SMS>
            <Geneve></Geneve>
            <OCDE></OCDE>
            <Group77>1</Group77>
            <Russophone></Russophone>
            <E9></E9>
        </Groups>
        <Regions>
            <Region xml:lang="en">Africa</Region>
            <Region xml:lang="fr">Afrique</Region>
            <Region xml:lang="es">África</Region>
        </Regions>
    </Country>
    <Country countryid="BN">
        <ISO3 xml:lang="en">BRN</ISO3>
        <ShortName xml:lang="en">Brunei Darussalam</ShortName>
        <ShortName xml:lang="fr">Brunéi Darussalam</ShortName>
        <ShortName xml:lang="es">Brunei Darussalam</ShortName>
        <LongName xml:lang="en">Brunei Darussalam</LongName>
        <LongName xml:lang="fr">Brunéi Darussalam</LongName>
        <LongName xml:lang="es">Brunei Darussalam</LongName>
        <Notes xml:lang="en"><![CDATA[]]></Notes>
        <Notes xml:lang="fr"><![CDATA[]]></Notes>
        <Notes xml:lang="es"><![CDATA[]]></Notes>
        <Capital>Bandar Seri Begawan</Capital>
        <TypeMem xml:lang="en">Members</TypeMem>
        <TypeMem xml:lang="fr">Membres</TypeMem>
        <TypeMem xml:lang="es">Miembros</TypeMem>
        <UNESCOdate>2005-3-17</UNESCOdate>
        <Holiday>2011-2-23</Holiday>
        <Langcoresp>en</Langcoresp>
        <Groups>
            <GroupEB>IV</GroupEB>
            <LDC></LDC>