<?xml version='1.0' encoding='UTF-8'?><!DOCTYPE Indicators [	<!ELEMENT CountryId (Country, Indicator, ValueId, Wesite)>	<!ELEMENT Country (#PCDATA)>	<!ELEMENT Indicator (#PCDATA)>	<!ELEMENT ValueId (#PCDATA)>	<!ELEMENT Website (#PCDATA)>	<!ATTLIST CountryId countryid CDATA #REQUIRED>	<!ATTLIST Indicator xml:lang (en|fr) "en" >	<!ATTLIST Website xml:lang (en|fr) "en" >]><Indicators><CountryId countryid="AF"><Country>Afghanistan</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>2</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AF/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AF/</Website></CountryId><CountryId countryid="AL"><Country>Albania</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>2</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AL/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AL/</Website></CountryId><CountryId countryid="AL"><Country>Albania</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AL"><Country>Albania</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="DZ"><Country>Algeria</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>7</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/DZ/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/DZ/</Website></CountryId><CountryId countryid="DZ"><Country>Algeria</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>4</ValueId></CountryId><CountryId countryid="DZ"><Country>Algeria</Country><Indicator xml:lang="en">Biosphere Reserves                                                                                                                                                                                                                                             </Indicator><Indicator xml:lang="fr">Réserves de biosphère                                                                                                                                                                                                                                          </Indicator><ValueId>6</ValueId></CountryId><CountryId countryid="DZ"><Country>Algeria</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>6</ValueId></CountryId><CountryId countryid="AD"><Country>Andorra</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>1</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AD/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AD/</Website></CountryId><CountryId countryid="AD"><Country>Andorra</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AO"><Country>Angola</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AO"><Country>Angola</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>8</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AR/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AR/</Website></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">Biosphere Reserves                                                                                                                                                                                                                                             </Indicator><Indicator xml:lang="fr">Réserves de biosphère                                                                                                                                                                                                                                          </Indicator><ValueId>13</ValueId></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>23</ValueId></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>2</ValueId></CountryId><CountryId countryid="AR"><Country>Argentina</Country><Indicator xml:lang="en">Creative Cities                                                                                                                                                                                                                                                </Indicator><Indicator xml:lang="fr">Villes créatives                                                                                                                                                                                                                                               </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AM"><Country>Armenia</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>3</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AM/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AM/</Website></CountryId><CountryId countryid="AM"><Country>Armenia</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>3</ValueId></CountryId><CountryId countryid="AM"><Country>Armenia</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>6</ValueId></CountryId><CountryId countryid="AM"><Country>Armenia</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>3</ValueId></CountryId><CountryId countryid="AU"><Country>Australia</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>19</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AU/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AU/</Website></CountryId><CountryId countryid="AU"><Country>Australia</Country><Indicator xml:lang="en">Biosphere Reserves                                                                                                                                                                                                                                             </Indicator><Indicator xml:lang="fr">Réserves de biosphère                                                                                                                                                                                                                                          </Indicator><ValueId>14</ValueId></CountryId><CountryId countryid="AU"><Country>Australia</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>8</ValueId></CountryId><CountryId countryid="AU"><Country>Australia</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>5</ValueId></CountryId><CountryId countryid="AU"><Country>Australia</Country><Indicator xml:lang="en">Creative Cities                                                                                                                                                                                                                                                </Indicator><Indicator xml:lang="fr">Villes créatives                                                                                                                                                                                                                                               </Indicator><ValueId>2</ValueId></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>9</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AT/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AT/</Website></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>2</ValueId></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">Biosphere Reserves                                                                                                                                                                                                                                             </Indicator><Indicator xml:lang="fr">Réserves de biosphère                                                                                                                                                                                                                                          </Indicator><ValueId>7</ValueId></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>6</ValueId></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>13</ValueId></CountryId><CountryId countryid="AT"><Country>Austria</Country><Indicator xml:lang="en">Creative Cities                                                                                                                                                                                                                                                </Indicator><Indicator xml:lang="fr">Villes créatives                                                                                                                                                                                                                                               </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AZ"><Country>Azerbaijan</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>2</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/AZ/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/AZ/</Website></CountryId><CountryId countryid="AZ"><Country>Azerbaijan</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                                                                                                                 </Indicator><ValueId>6</ValueId></CountryId><CountryId countryid="AZ"><Country>Azerbaijan</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="AZ"><Country>Azerbaijan</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>1</ValueId></CountryId><CountryId countryid="BS"><Country>Bahamas</Country><Indicator xml:lang="en">Memory of the World                                                                                                                                                                                                                                            </Indicator><Indicator xml:lang="fr">Mémoire du monde                                                                                                                                                                                                                                               </Indicator><ValueId>2</ValueId></CountryId><CountryId countryid="BH"><Country>Bahrain</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>2</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/BH/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/BH/</Website></CountryId><CountryId countryid="BH"><Country>Bahrain</Country><Indicator xml:lang="en">UNESCO Chairs                                                                                                                                                                                                                                                  </Indicator><Indicator xml:lang="fr">Chaires UNESCO                                                                                                                                                                                                                                                 </Indicator><ValueId>2</ValueId></CountryId><CountryId countryid="BD"><Country>Bangladesh</Country><Indicator xml:lang="en">World Heritage                                                                                                                                                                                                                                                 </Indicator><Indicator xml:lang="fr">Patrimoine mondial                                                                                                                                                                                                                                             </Indicator><ValueId>3</ValueId><Website xml:lang="en">http://whc.unesco.org/en/statesparties/BD/</Website><Website xml:lang="fr">http://whc.unesco.org/fr/statesparties/BD/</Website></CountryId><CountryId countryid="BD"><Country>Bangladesh</Country><Indicator xml:lang="en">Intangible Cultural Heritage                                                                                                                                                                                                                                   </Indicator><Indicator xml:lang="fr">Patrimoine culturel immatériel                                                                                                                                    